apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-demo
spec:
  accessModes:
    - ReadWriteOnce # Must be compatible with the PV it's binding to
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi # Specifies the amount of storage requested
  volumeName: ebs-pv-demo # Must match the exact name of the PV